### ISSUE TITLE
USB issues. 

### ISSUE THREAD

**Issue by Orvis25** [dborth/fceugx#344]
Hey, so I recently installed Fceultra GX and have discovered a massive issue that is preventing me from playing games.

When I launch a game and start playing, everything is fine. But after like 10 min of playing if i hit the home button to bring up the menu so i can save, my HDD turns off, and the wii no longer recognizes it until I hard reset both the wii, and unplug my hdd.

I think this is an programming issue with something that Snes9x GX. FCEUltraGX, WiiSX and VBA GX use because I have the same problem in all three.

Now i know it is not an HDD issue because I have USB Leader GX installed, and I can play games for hours, close and change games after a few hours without any issues.

Anyone know if this will be patched, or know of a fix?

**Comment by dborth** [comment]
Sounds like your hard drive is going to sleep. Sorry but the code is not going to get any better unless someone submits a patch. So I'd suggest to use an SD card. They cost next to nothing.
