### ISSUE TITLE
Channel doesnt load.

### ISSUE THREAD

**Issue by xXCheeseWizardXx** [dborth/fceugx#348]
i have installed this and its latest channel installer onto my wii u's vwii but whenever i try to load it up from the channel it leaves the screen black. but the games work when i load them from the homebrew channel. any help? (no channels work i have also tried the snes9xgx channel and the gba channel none work)

**Comment by dborth** [comment]
Sorry, this isn't a support forum. Try some other place like gbatemp.net for help.
