### ISSUE TITLE
Minor issues with fceugx 3.3.9

### ISSUE THREAD

**Issue by AlphaVyas** [dborth/fceugx#351]
- sound no longer coming from the menu (BGM and SFX) just controller vibration remains active. 

- need to manually add the "screenshots" folder or else preview screenshots won't find the directory ending up with a fail message.

**Comment by dborth** [comment]
The screenshots dir is now auto-created. The sound was explicitly disabled in 3.3.9. There's some debate as to whether it should be in or not.
