### ISSUE TITLE
Screenshots not taken if Screenshots folder doesn't exist.

### ISSUE THREAD

**Issue by ppsspp213** [dborth/fceugx#354]
Something like this needed.

set Screenshots_DIR=
if not exist %Screenshots_DIR% (mkdir %Screenshots_DIR%)

Also the screenshots are more like boxart thumbnails since they showup in the preview window next to the rom title, i've tried adding my own custom images but it only seems to accept 8-bit 640x480 .png with no alpha channel, with alpha channel it stretchs the width of the image x2 and turns it monochrome with lines running through it, 24-bit .png cause it freeze or crash, even though the 24-bit 640x480 in-game screenshots work fine, which poses another question why save as 24-bit when the NES is only YPbPr 64-color palette?

**Comment by dborth** [comment]
The screenshots dir will now be created if it doesn't exist. The PNG compatibility is limited. You'll just have to find a way to produce PNGs it supports. The one's I've tried work fine...
