### ISSUE TITLE
(Request) WiiU Gamepad Support.. 

### ISSUE THREAD

**Issue by Ploggy** [dborth/fceugx#360]
Hi, it's recently become possible to add WiiU Gamepad support to vWii Emulators/Homebrew via WiiVC.
Could you add Fix94's Gamepad patch to your Emulators please?

https://github.com/FIX94/libwiidrc
from fix's readme:

> > libwiidrc
> > 
> > This is only usable with a sepcial patched fw.img and homebrew injected into a wiiu vc title, details on the patches are below.
> > The usage is quite simple, call WiiDRC_Init on boot and after that call WiiDRC_ScanPads every time you update your pad inputs.
> > See the "demo" folder for an example on how to use it in a bit more detail.
> > Both compiled Library and Demo can be grabbed from the Releases tab.
> 
>

**Comment by wicksand420** [comment]
Is this emulator dead? All signs point to yes, too bad.

**Comment by askotx** [comment]
dborth have said that any PR are welcome, @wicksand420 if you want to contribute to this project go and make a pull request, stop whining please.

**Comment by wicksand420** [comment]
who's whining, I stated a fact that no one is working on this, and only said it once, that is far from whining
