### ISSUE TITLE
No working GameCube releases after version 3.3.4

### ISSUE THREAD

**Issue by boktai1000** [dborth/fceugx#361]
It appears that builds for GameCube have stopped after the 3.3.4 release. I did try booting the .DOL file on my GameCube using SWISS of version 3.3.9 but had no such luck.

**Comment by bladeoner** [comment]
Please check if this works for you:
[FCE.Ultra.GX.3.4.0.zip](https://github.com/dborth/fceugx/files/1638536/FCE.Ultra.GX.3.4.0.zip)

**Comment by boktai1000** [comment]
@bladeoner this did indeed work for me, I was greeted with some nice menu music and saw that it listed version 3.3.9 at the top, but I'm sure it's just because the build you posted didn't change the version number.

That being said I'd also like to make mention why I believe I encountered no working versions after 3.3.4. I am not building these released myself, and only using what's provided at https://github.com/dborth/fceugx/releases in which case 3.3.4 the only build they are providing is for the Wii it seems, I was attempting to use that on GameCube.

Regardless, your build did indeed work - and for someone that isn't compiling versions themselves it provides me with the ability to use the latest version. I hope this makes sense and I really appreciate your response and hope this information helps! As development continues I sure would appreciate GameCube compiled versions to be published alongside the Wii versions!
