### ISSUE TITLE
Mayflash NES SNES to Wii WiiU adapter not fully compatible...?

### ISSUE THREAD

**Issue by littlebigboss12** [dborth/fceugx#364]
https://www.amazon.ca/Mayflash-NES-SNES-Controller-Adapter/dp/B00B2K0C8M

Got this with the hopes of using original NES and SNES controllers with FCEU GX and SNES9X GX, but it doesn't seem to function correctly. It recognized the SNES controllers as 'classic controllers' immediately but after a few seconds the emulator would skip frames erratically and the controller inputs would act as though they were being pressed when they weren't (this happens in the GUI menu for both emulators as well).

This was tested with two different Mayflash adapters and two different (tested working fine) SNES controllers, and a Luigi Wiimote Plus on my WiiU vWii with Super Mario Bros. for FCEU GX and Star Fox and Super Mario World for SNES9X GX.

I suspect the Mayflash adapters do something the emulators don't like, because as soon as I unplugged it from the Wiimote, everything worked as normal (framerate and controller response normal). Is there anything that can be done to fix this? I'll submit whatever information I can.

**Comment by askotx** [comment]
We get no adapter to test, anyway PR are welcome
