### ISSUE TITLE
Artwork/Covers options and path not available

### ISSUE THREAD

**Issue by Lesbinary** [dborth/fceugx#372]
Hi. I was trying to use the Wii as a cheap NES/SNES Classic Mini using the "GX" emulators and I got stuck with the game covers. I observed that artwork and covers options are not available in FCE Ultra GX emulator, but they are in Snes9x GX, both are latest versions. Is this unavailable by any technical reason?

**Comment by dborth** [comment]
No one has added it. That's why. But you can use the screenshots feature and then put whatever artwork you want, there's no reason it has to be a screenshot.
