### ISSUE TITLE
These emulators do not recognize/see my FAT32 USB powered HDD, when i hide it from the wii u 

### ISSUE THREAD

**Issue by morpheousx** [dborth/fceugx#374]
I just discovered that none of the emulators below, detect my USB powered HDD, Formatted to FAT32, when i set the hdd to, "hidden" so the wii u doesn't nag me to format it. I run all 3 emulators among others, via my vwill menu.

When i unhide the hdd, the emulators see the hdd and they work as normal. is there a work around for this or are there versions of these emulators that support hidden hdd drives?

vbagx
snes9xgx
fceugx

**Comment by dborth** [comment]
Use an SD card
