### ISSUE TITLE
 FCEUltraGX-Channel-Installer

### ISSUE THREAD

**Issue by wolfniggr** [dborth/fceugx#375]
Was hoping someone could fix the forwarder to work with a 128gb sd card. When you click on start it'll just go back to the main Wii menu.

Did some research online and found out this is an old problem no one had fixed. This is probably due to the fact that hardly anyone used a high capacity SDXC card, but due to the substantial drop in pricing they've become the better deal in dollar per gb.

Thank you

**Comment by dborth** [comment]
Was the card formatted as FAT32? You can't do that with Windows, you'd have to use a program like fat32 formatter to do that. https://fat32-format.en.softonic.com/

But even if it doesn't work, I'm not looking into SD compatibility issues.
