### ISSUE TITLE
GameCube controller and settings

### ISSUE THREAD

**Issue by stubl** [dborth/fceugx#379]
I want to first thank developers of this emulator and say I appreciate this emulator a lot, I did come across some issues in the latest fceugx and thought I'd just compile those below

* The GameCube controller doesnt seem to work for me in the latest fceugx tho wiimote works
* Game Settings - Video Scaling isnt set Default by default and so makes the screen squished on Wiis not set to widescreen aswell this setting is unlike snes9xgx so there is inconsistency among GX emulators there
* Covers and Artwork support would be good for fceugx going back to consistency among snes9xgx and also some people like and use covers and artwork
* Also I think cropping set vertical would be better default cropping more just this is how NES would be on CRT television

again thank you for the emulator and other than those things its a great emulator I use all the time

**Comment by dborth** [comment]
GameCube controller is fixed. Thanks for reporting that.
Video scaling default is now only set to widescreen correction if Wii is in widescreen.
Cover and artwork was just added in a PR.
Default cropping is now set to be both hor and vert. You're right about vert only but for games like SMB3 there's ugly tearing on the left/right so I think both is a better default.
