### ISSUE TITLE
Network Load Location - Crash

### ISSUE THREAD

**Issue by meluvalli** [dborth/fceugx#385]
Hello.  

If you set LOAD location to Network, it'll initialize network and work!  

However, next time you load FCE, it'll crash.  Can't re-launch it.  Have to manually edit settings file and change "LoadMethod" back to anything other than 4 in settings.

This also happens in vbagx.

This is a new issue.  Didn't happen in my old version (3.3.4).

**Comment by dborth** [comment]
[fix.zip](https://github.com/dborth/fceugx/files/2810778/fix.zip)

Okay, I think I've fixed it. Please try the attached version and let me know.

**Comment by meluvalli** [comment]
Yep!  That fixed it :)  Thank you!  I'll wait for the VBAGX update as well!

Thanks again!
