### ISSUE TITLE
(Request) USB Gamepad support

### ISSUE THREAD

**Issue by Magicrafter13** [dborth/fceugx#386]
Would anyone be willing to implement USB Controller support like Nintendont?
More specifically in my case, I'd love to use my USB NES controller adapter (maps with Xinput), for that authentic feel, but I'm sure some people would like using an Xbox controller as well.

**Comment by dborth** [comment]
This is not for feature requests

**Comment by GB-CG** [comment]
@Magicrafter13 Why not just use a NES-to-GC adapter made by Raphnet-tech?

**Comment by Magicrafter13** [comment]
> This is not for feature requests

Sorry, I just saw these and thought they were.
https://github.com/dborth/fceugx/issues/362
https://github.com/dborth/fceugx/issues/360
https://github.com/dborth/fceugx/issues/357
https://github.com/dborth/fceugx/issues/279
https://github.com/dborth/fceugx/issues/250
https://github.com/dborth/fceugx/issues/122

So, where would I submit a feature request?

**Comment by Magicrafter13** [comment]
> @Magicrafter13 Why not just use a NES-to-GC adapter made by Raphnet-tech?

Didn't know that was a thing.
