### ISSUE TITLE
Switch back from 480p to 480i on unsupported screens

### ISSUE THREAD

**Issue by shroom2k** [dborth/fceugx#388]
What steps will reproduce the problem?
1. Start up FCEUGX on 480p-supported display
2. Start up any game
3. In FCEUGX, select 480p display mode
4. Turn off Wii
5. Connect Wii to display that only supports 480i/240p
6. Start up FCEUGX
7. Start up any game 

What is the expected output? What do you see instead?

Expected to see game and menu running in 480i. Instead, I only see black screen, because the game is apparently running in 480p. There is no way to switch back - the menu also cannot be viewed after the game is run, I only hear the menu sounds, but can't see it.

What version are you using? On GameCube or Wii?

Wii Version 3.4.2

Are you using the official build (from the downloads page or auto-update)?

Yes

Please provide any additional information below.

Of course, I can go back to 480p display and switch back there, but the Wii performs 480i/480p switch automatically, so I expect the homebrew to follow. I believe the homebrew should automatically determine available video modes and make a switch, if an unavailable one is used.

**Comment by dborth** [comment]
Not going to fix this.
