### ISSUE TITLE
Rebuild Wii 480p fix

### ISSUE THREAD

**Issue by tqhoang84** [dborth/fceugx#391]
I saw that your Snes9xGX v4.4.4 has the Wii 480p fix integrated.  Could you also make a new release of FCEUltraGX and VisualBoyAdvanceGX with the fix as well?

**Comment by dborth** [comment]
What fix?

**Comment by tqhoang84** [comment]
The commit to libogc is here:
https://github.com/devkitPro/libogc/commit/b90c9415baae86252448993806a1ce1521440a28

I checked your Snes9xGX v4.4.4 release and it appears to have the "fixed byte pattern" in the executable.

FWIW, the user blackb0x@gbatemp describes the "byte patterns" here:
https://gbatemp.net/threads/usb-loader-gx-480p-fix.536672/#post-8606161

**Comment by dborth** [comment]
Ah okay. Then the next time I make a release this will get picked up.
