### ISSUE TITLE
(Question) Does the channel installer work on vWii?

### ISSUE THREAD

**Issue by HTV04** [dborth/fceugx#392]
I would like to use the channel forwarder on the vWii, but I'm unsure if it works properly. I've seen a similar issue where a user reported that the forwarder does not work on the vWii. Has this issue been fixed?

**Comment by dborth** [comment]
No it doesn't, it requires changes to work on vWii. If someone makes those changes and sends me a WAD I'll post it here, otherwise you're on your own.

**Comment by HTV04** [comment]
I could fix it if the WAD was created with CustomizeMii. Do you have the base WAD?
