### ISSUE TITLE
Return to loader Gamecube port

### ISSUE THREAD

**Issue by 60fpshacksrock** [dborth/fceugx#395]
Would it be possible to be able to boot to autoexec.dol or boot.dol in sdgecko slot b?
I ask because I get freezes when using this option on GC.  Also I was wondering if this request could also added to the other GC ports like snes9xgx.

**Comment by dborth** [comment]
Sorry but I can't help you with this. I don't own a sdgecko and I'm not familiar enough with what would need to be done.

**Comment by 60fpshacksrock** [comment]
Swiss can now do this, just so you know.
