### ISSUE TITLE
Boxart, screenshots, etc. Broken on GC version.

### ISSUE THREAD

**Issue by 60fpshacksrock** [dborth/fceugx#396]
As the title says the PNG loading for boxart and such is broken. 

It displays instead a transparent flickering red background. Same also for snes9xgx. Untested on other GX ports.

**Comment by dborth** [comment]
Did it used to work for you on an earlier version (if so, which one?) and now it doesn't? Have you tried the Wii version, does the same files work there?
There's specific requirements for PNG format and size limitations that would also explain why it doesn't load. Does this file work for example?
![Super Mario Bros  3](https://user-images.githubusercontent.com/11741529/74582873-6e1ba300-4f7e-11ea-9cf4-6c4191641ac8.png)

**Comment by dborth** [comment]
fixed in new release

**Comment by 60fpshacksrock** [comment]
Sorry that I couldn't reply earlier than this. But yes ever since it was added it worked fine on the Wii versions with me.
I can't remember it ever working on the GC version before. Thanks for checking into it and fixing it.

Maybe it's just me but the games somehow look more proper on the GC than Wii. 
At least that's my preference.
