### ISSUE TITLE
backing out of rom folder takes you to root

### ISSUE THREAD

**Issue by supersonicjc** [dborth/fceugx#397]
on the newly complied version 3.4.4 when you try to go up one level in the rom directory there are now 2 folders both labeled "up one level" if you select either one it takes to you the root directory instead of going back one folder, my set up has 6 rom folders to divide them up and instead of being able to just go up one level I get tossed back to asking where the emulator needs to grab the files.
normally I guess would be roms> us> rom name but now each time you want to switch to say translations you now click on up one level and go sd card> fceugx> roms and so on to get what use to be a simple back click,

**Comment by CrewMdk** [comment]
The same happens to me on Wii or the Dolphin Emulator.

![0000000100000002-2](https://user-images.githubusercontent.com/10386171/74566407-02631700-4f39-11ea-85e3-241572a460bf.png)

**Comment by dborth** [comment]
fixed in new release
