### ISSUE TITLE
Request: Filtering options to make FCEUGX more accurate

### ISSUE THREAD

**Issue by Nashismo** [dborth/fceugx#400]
I don't know if this is possible, but in the Sega emulator for Wii, there are this awesome filters: Composite, S Video and RGB and they look really accurate when using a CRT.

Could you implement something like this on FCEUGX?

I don't loose anything asking, thank you very much and please close this thread if this is impossible, thank you.

Nashismo.

**Comment by dborth** [comment]
I'm sure it's possible, but it's beyond my current understanding to do. if someone else does it, I'll add it.
