### ISSUE TITLE
Gamecube version hangs up on filebrowser screen since v3.4.4

### ISSUE THREAD

**Issue by kiwanowski** [dborth/fceugx#404]
Since version v3.4.4 the Gamecube version of the app hangs up on boot - on the filebrowser screen

I boot it using the latest swiss, I dont have a disc drive. I have a memory card in slot a and an sd card in slot b, no sd2sp2 (not yet).

v3.4.3 works great :)

I have the same behaviour on Snes9xGX v4.4.5 and v4.4.4

I think its the same issue as this one - https://github.com/dborth/snes9xgx/issues/906

**Comment by kiwanowski** [comment]
I have noticed that commenting out:

MountFAT(DEVICE_SD_PORT2, SILENT);

in fileop.cpp works as a workaround

**Comment by dborth** [comment]
that's great to know, thanks for investigating

**Comment by dborth** [comment]
@Pwedge any idea what's going on here?

**Comment by dborth** [comment]
[snes9xgx-gc.zip](https://github.com/dborth/fceugx/files/4284944/snes9xgx-gc.zip)

Does this work?

**Comment by kiwanowski** [comment]
Nope, still hangs up on the first screen

**Comment by dborth** [comment]
Ok. I've disabled the mounting.
