### ISSUE TITLE
rom selection isnt remembering

### ISSUE THREAD

**Issue by supersonicjc** [dborth/fceugx#406]
on the last version on this emu and the snes emu when you selected a rom file then after played and quit the emulator the system would remember what rom you played last when you ran it, as of the latest revision just released it jumps up 20 or so titles in the rom list now instead of remembering what game you played

**To Reproduce**
start up emu and play any game, quit emu and reboot emu 
**Expected behavior**
emu should remember what game you last played when you ran it

this is happening on both the nes and snes updates if need be I can submit a bug fix request in there as well

**Comment by dborth** [comment]
That's never been a feature. It only remembers the last folder. Not the game.

**Comment by supersonicjc** [comment]
honestly im not sure on that one, the previous version not only remembered what folder you played last but it remembered what the last game that was played before it was closed, now instead it jumps to a random rom 20 or so titles up?

**Comment by dborth** [comment]
I took a look and you're right, this is a feature. And I tested it, and it's working for me. It only works if you actually load the game though, not if you scroll to a game and then exit.

**Comment by supersonicjc** [comment]
that was what I was trying to explain, when I do that on both the nes and the snes emu and when I quit to go to another emu then come back to this or the snes the game save jumped up at least 20 or so titles... so not sure what is going on with my download, I will redownload the current build and try again and see if I still get the same issue

**Comment by supersonicjc** [comment]
so I went and retested both emulators from fresh downloads and I still keep getting the same issue, it does change sometimes to jump only 10 roms to sometimes up to 40 roms up, tested from a start up and trying to load up the emulators after playing another emulator, not sure what is happening there with the emulator but it isn't remembering what the last rom that was played after I quit the emulator
