### ISSUE TITLE
Cheats flag is swapped on gx ports

### ISSUE THREAD

**Issue by 60fpshacksrock** [dborth/fceugx#417]
This is a longstanding glitch I noticed but never mentioned it until now.

When cheats are enabled on the PC version they are disabled on the gx port and vice versa. Snes9x simply ignores if cheats are enabled or not and they are always disabled until you enable them.

**Comment by dborth** [comment]
This is working just fine. I cannot reproduce. If I'm on the GX version, cheats are working fine. They're on when they're turned on and off when they're turned off. If you're talking about switching between PC and GX or something like that, I'm not going to help you there.

**Comment by 60fpshacksrock** [comment]
I meant what I said. They're swapped for me.

Unsure why but thanks for taking a look at it anyway.
