### ISSUE TITLE
Long cheat names cause issues

### ISSUE THREAD

**Issue by 60fpshacksrock** [dborth/fceugx#418]
If the name of a one or more cheats is kind of long, the on/off option will have part of the text in it. You try to enable the code and it will say it's on but it isn't because there is no effect.
If you go back to the game after trying to enable and then go back to the list it will be disabled again with glitched text. 

The problem for me I'm not sure how many characters are allowed in the name. The easiest way to test is to download a cheat file from gamehacking.org and see for yourself.  If not, sometime later I can post a pic of it.

**Comment by dborth** [comment]
You're right, someone increased the length to 300 when the max size is only 100. That's now fixed.
