### ISSUE TITLE
Update on vWii WADs

### ISSUE THREAD

**Issue by HTV04** [dborth/fceugx#420]
(I originally posted this on the old issue, but then I remembered that I can't re-open the issue.)

Hey, I just noticed your replies. I'm really sorry for not updating you on this. I actually had the files sitting on my drive for a while, but I didn't want to release them until I fully tested them. I'm really sorry about this, and I'm glad you found a way to make working ones yourself.

So you know I'm not lying, I've attached all of the fixed, fully tested WADs (including one for WiiMC, which it seems like you haven't made yet), dated March 19 (I had ones from a different computer, which were the ones I had in December, but I decided to recompile them on my new computer, let me know if you want those too).
[fixed.zip](https://github.com/dborth/fceugx/files/4707589/fixed.zip)
An annoyance about them is that they load in 4:3. I don't know if that's something you've fixed in the latest FCEU GX (and etc.) yet, though.

Maybe I should be more prepared when making a claim that I could make vWii WADs for you. I'm really sorry. The main fear I had that prevented me from releasing them was whether they worked at all. The reason I didn't test them was... Laziness. I had my Wii U completely unplugged and I didn't want to hook my Wii U up again.

I'm really sorry about this. Really. Hopefully next time (if there is), I won't take 10 years to help with anything.

Oh, and by the way, if it helps, here's the code related to enabling widescreen on vWii for the OHBC:
```
#ifdef ENABLE_WIDESCREEN
	if (CONF_GetAspectRatio() == CONF_ASPECT_16_9) {
		gprintf("aspect: 16:9\n");
		view_width = 852; // 16:9
		view_height = 480;

		vmode->viWidth = 672;

		widescreen = true;

		if (is_vwii()) {
			// poke DMCU to turn off pillarboxing
			write32(0xd8006a0, 0x30000004);
			mask32(0xd8006a8, 0, 2);
		}
	} else {
#endif
		gprintf("aspect: 4:3\n");
		view_width = 640;
		view_height = 480;

		vmode->viWidth = 672;

		if (is_vwii()) {
			// poke DMCU to turn on pillarboxing
			write32(0xd8006a0, 0x10000002);
			mask32(0xd8006a8, 0, 2);
		}
#ifdef ENABLE_WIDESCREEN
	}
#endif
```
You might be able to modify it and add it to your apps.

**Comment by askotx** [comment]
If you know how to fix and tested it well make a Pull Request please, dont create an issue for this.

**Comment by dborth** [comment]
I already fixed the 4:3 issue on the ones I made. So they don't have that same issue. The challenge was disabling memprot in the forwarder in order to poke that register to fix the aspect ratio.

**Comment by HTV04** [comment]
That's good. I haven't tested your WADs yet, so I didn't know if you had patched it out. Again, sorry for the trouble.
