### ISSUE TITLE
2 NES 2.0 homebrew not working

### ISSUE THREAD

**Issue by INFU-AV** [dborth/fceugx#421]
**Describe the bug**
Pulsar and PR8, music making homebrew doesn't start and show the error page.

**To Reproduce**
PR8 and Pulsar are available this page:
https://woolyss.com/chipmusic-chiptrackers.php?s=Nintendo
right at the bottom! pr8.nes and pulsar.nes
Just load them as any other NES rom file
emulator will show up screenshot included.

**Expected behavior**
Error should not be seen!
After loading them without save they can require a restart, but then they should work absolutely normal, especially when newest FCEUX from github supports them no problem!

**Screenshots**
![2020-05-29 10_44_12-Nintaco](https://user-images.githubusercontent.com/66220663/83361344-35aea200-a380-11ea-97cc-1a50f14839e6.png)

Also, thanks for this emulator! It's really wonderful and I see this bug report as opportunity to make it even better!

**Comment by dborth** [comment]
This isn't a bug. This is a feature request to update this emu to support this. If someone submits a PR, it'll happen.
