### ISSUE TITLE
emulator wont remember last game played

### ISSUE THREAD

**Issue by supersonicjc** [dborth/fceugx#424]
**Describe the bug**
the emulator when you first boot up the emulator it should remember the last game that was played before you close the emulator out and instead when you boot it up the emulator jumps up your game list from 10 to 30 titles higher

**To Reproduce**
start the emulator up and the expected behavior should be that the last game you had played before the emulator was played should be right there however it will always jump up from 10 to 30 titles higher
**Expected behavior**
version 3.4.5 this feature was still working just fine but the last 2 updates this has been broken, I did report it and mentioned it wasn't working but it was closed even after I mentioned that this was in fact a feature of the emulator... the only work around im finding currently is that the newly rereleased channel app doesn't have this issue but it still has this issue on the homebrew channel so not sure what is broken there

**Screenshots**

**Comment by dborth** [comment]
This is likely a timing issue because of a delay between when your device is mounted and ready and when the file browser starts up and tries to list/display the contents. I have absolutely no intention of looking at this. If someone else fixes it and makes a PR, this will be fixed. Otherwise it won't.

Please stop harassing me.

**Comment by supersonicjc** [comment]
im sorry you feel that my request is harrasment…. I will try a new sd card and see if that fixes said issues with the newest builds... I only reported these as like I said prior it worked and was a feature but now it no longer works as intended, thank you for at least taking the time to reply
