### ISSUE TITLE
PAL games audio hiccups

### ISSUE THREAD

**Issue by Flo85o** [dborth/fceugx#430]
**Feature requests will be closed immediately!**

**Describe the bug**
Audio hiccups every 20 seconds when playing PAL games like Ufouria and Asterix.

**To Reproduce**
Load a PAL game and listen to the audio

**Expected behavior**
The audio should not glitch every 20 seconds but should play as smooth as NTSC games.

**Screenshots**
Audio sample (Asterix PAL): https://u.pcloud.link/publink/show?code=XZPi6ckZNGemXT2vvt8oUR6CegEJUJpPBR0y

**Comment by dborth** [comment]
Are you playing on an NTSC or PAL TV?

**Comment by Flo85o** [comment]
Hi dborth, thank you for the lightning fast reply, got a European tv Samsung UE22H5610AW

**Comment by dborth** [comment]
So I've only tested NTSC on NTSC and pal on ntsc. I don't have a pal tv (50hz) so I don't have a way to test that

**Comment by Flo85o** [comment]
Hi dborth, that is unfortunate to hear. So that hiccup is not present when running a pal game on your ntsc wii in combination with your 60hz tv? I thought fceugx was standalone and that it's behavior stays the same when using a 50hz or 60hz screen (just like running it on pc or gamecube). I've recorded the audio of a real pal nes game running of a pal nes and compared the track with the recorded audio of the same game running on fceugx 3.4.7. The result is that fceugx plays the audio slightly faster, so maybe the sound rate for pal games is a bit off. Also, this problem was not present in older builds of fceugx but occurs in the more recent builds.

**Comment by Flo85o** [comment]
Hi dborth, i just tried a few old versions but i can't find the specific version where the hiccups started. Maybe it's one of the earliest versions, i can't remember. The only thing i can hear is that the hiccups are less frequent in for example build 3.4.3.

**Comment by dborth** [comment]
should be fixed. Tanooki16 calculated new audio rates for PAL.
