### ISSUE TITLE
GCSettings.videomode not working on main screen

### ISSUE THREAD

**Issue by adubkov** [dborth/fceugx#433]
I'm facing this bug on Gamecube.

I configured video mode to `480i` in `settings.xml`. It works only for games, but on the main screen it seem that it does detects the video mode. When I back to main screen after running the game, it does use correct video mode. 

So, there is a bug that main screen does not use video mode from settings.xml.

It is annoying because in my case detection sets video mode to `480p` and unfortunately my CRT dos not support it.

**Comment by dborth** [comment]
Not really a bug, this is the way it's implemented. on Gamecube if you're using a component cable we assume 480p. Not going to change this.

**Comment by adubkov** [comment]
Well, that doesn't work for almost all CRT with component cable. Even in swift you can force 480i by pressing `L`.
There could be an option to use `GCSettings.videomode` for menus. Something like `GCSettings.force_videomode_in_menu`.

**Comment by adubkov** [comment]
Hey @dborth 
I would like build it with this workaround for myself. Will it be enough to comment this line out?
https://github.com/dborth/fceugx/blob/34e45f4d09fdbaf06cdf9ffac3bf2f582bd6505d/source/fceugx.cpp#L379
