### ISSUE TITLE
Import Dendy mode (NTSC/PAL hybrid timing) from main FCEUX branch.  

### ISSUE THREAD

**Issue by eugene-s-nesdev** [dborth/fceugx#434]
Hello, **fceugx** developers.

Can you import dendy-mode support from lastest fceux source?
It's actually presents in official FCEUX 2.2.3 as well, as advanced overclock
(Vblank and Postrender overclock both methods are available)

"Dendy-mode" is name for pirate PAL timing, which allow to run most of NTSC games (Japan, USA) on 50 Hz without glitches, with correct DPCM sound pitch also, unlike official PAL NES timing. 
No need to "autodetect" it via "auto-region". It must be set by user, and emulator should "remember" it.

**Complete Information:**
[Cycle Reference Chart - nesdev wiki](http://wiki.nesdev.com/w/index.php/Cycle_reference_chart)
[Table of differences between NTSC, official PAL NES and Dendy pirate PAL timings](https://user-images.githubusercontent.com/13199529/97995401-82971880-1df7-11eb-87fe-3750db5ace1a.png)
[Global Nesdev F.A.Q.](https://forums.nesdev.com/viewtopic.php?f=2&t=20931)

**Dendy timings have specific behavior, so here are region test roms:**:
[240pee](http://forums.nesdev.com/download/file.php?id=6415) by Tepples (Damian Yerrick) must show timing:
![240pee_timing](https://user-images.githubusercontent.com/13199529/98018347-7cae3100-1e11-11eb-9571-927bab3019d7.png)
**note:** cycles/line and cpu speed will show a bit lower values on FCEUX, due it sprite evaluation inaccuracy.

[Overclock test](http://forums.nesdev.com/download/file.php?id=2826) by Tepples (Damian Yerrick):
![overclock_png](https://cloud.githubusercontent.com/assets/13199529/8929553/0bfa1508-352f-11e5-9808-dace1956dd1c.png) 
**note:** cycles/line and cpu speed will show a bit lower values on FCEUX, due it sprite evaluation inaccuracy.

"Battletoads and Double Dragon (U).nes" must have glitches like this:
![BTDD_Dendy](https://user-images.githubusercontent.com/13199529/98018844-15dd4780-1e12-11eb-894f-95d1631357d4.gif)

"Choujin Sentai - Jetman (J)" intro glitch:
![Jetman_Dendy](https://user-images.githubusercontent.com/13199529/98018896-2b527180-1e12-11eb-9afa-3ed28004214c.gif)

Noise and DMC APU pitch tables are same as NTSC NES/Famicom,
so Sunsoft NTSC games must have [correct pitch](http://hwm.us.to/emustuff/Forum/Journey_to_Silius_Title.mp3) 

As i already said, dendy mode is fully implemented in fceux 2.2.3 since 2016, so you're need only add it to your branch and make region switch toggle, like it was done [**here**](https://github.com/libretro/libretro-fceumm/issues/51).

**Comment by dborth** [comment]
[fceugx-wii-dendy.zip](https://github.com/dborth/fceugx/files/5495458/fceugx-wii-dendy.zip)
 Does this work?

**Comment by eugene-s-nesdev** [comment]
Hm, i don't see it. Is it here?
![fceugx](https://user-images.githubusercontent.com/13199529/98275881-3b02bf00-1fa6-11eb-9b4c-aee829ab1f65.png)

**Comment by eugene-s-nesdev** [comment]
Tested on hardware, dendy mode works incorrect in all output modes (50Hz/576i, 60Hz/480i, EDTV/HDTV/480p)
Sound tempo on Dendy should be 50Hz, but it on this build it works at 60Hz (like NTSC NES)  and have stuttering

**Comment by dborth** [comment]
Ah I didn't realize that. In that case, here's one final test. Let me know if it's closer. Fixed that menu selection bug where Dendy wasn't showing up too, but looks like you got around that.

[fceugx-wii-dendy-v2.zip](https://github.com/dborth/fceugx/files/5505224/fceugx-wii-dendy-v2.zip)

**Comment by eugene-s-nesdev** [comment]
Thank you.
This build works good and correct on hardware, but anyway i'll do deeper test.

Strange things with emulators, and i don't understand what's happened:
Dolphin and Dolphin Ishiiruka (jit cpu recompiler + DSP LLE recompiler)

**Dolphin at 60Hz:**
_settings -> wii -> usePAL60(euRGB60)
[wii at 60Hz(480i) instead of 50Hz(576i)]_
= ENABLED

FCEUGX NTSC(60Hz) - normal behaviour
FCEUGX PAL(50Hz) - timing rom test sometimes give wrong values
FCEUGX Dendy(50Hz) - timing rom test sometimes give wrong values, sound stutters

**Dolphin at 50Hz:**
_settings -> wii -> usePAL60(euRGB60)
[wii at 60Hz(480i) instead of 50Hz(576i)]_
= DISABLED

FCEUGX NTSC(60Hz) - timing rom test sometimes give wrong values
FCEUGX PAL(50Hz) - normal behaviour
FCEUGX Dendy(50Hz) - normal behaviour

FCEUX Core must give this values:
![fceux](https://user-images.githubusercontent.com/13199529/98466108-77206480-21de-11eb-97ca-7287ec8fae3a.png)

Can you test on hardware too, please?

**Comment by eugene-s-nesdev** [comment]
Tested on Wii (50Hz/576i, 60Hz/480i modes)
All works correct.
So i don't know what's happened on Dolphin.

Additional tests on another hardware would be nice too

**Comment by dborth** [comment]
thanks for testing, it's much appreciated! I've committed the code since at a minimum it won't impact PAL/NTSC settings, so if people do have problem with the Dendy option they don't have to use it.
