### ISSUE TITLE
Robocop 2

### ISSUE THREAD

**Issue by mxpxpxpx** [dborth/fceugx#435]
**Feature requests will be closed immediately!**

**Describe the bug**
I am trying to play the ROM Robocop2 and all I get is a blank screen. It plays fine on the desktop version

**To Reproduce**
Load Rom

**Expected behavior**
The game to load

**Screenshots**

**Comment by mxpxpxpx** [comment]
Sorry I forgot to mention it is in the Wii version of FCEU GX. I have tried multiple versions of the ROM and same issue. Thank you.

**Comment by dborth** [comment]
Tried it myself. Works fine.
