### ISSUE TITLE
Issue with covers and/or PNG files

### ISSUE THREAD

**Issue by sublime8696** [dborth/fceugx#438]
Upgrading from 3.4.6 to 3.4.8 I lose functions of covers in PNG format on Wii. It's possible this is no longer supported and I missed it.

**Comment by dborth** [comment]
Looked a little closer...I think images are now restricted to 512x512 at most since they get scaled down smaller than that anyway. Perhaps your covers are bigger?

**Comment by sublime8696** [comment]
> Looked a little closer...I think images are now restricted to 512x512 at most since they get scaled down smaller than that anyway. Perhaps your covers are bigger?

That did the trick! My covers were 800x600. I did a batch conversion of my covers to 512x384 and all is good now. My apologies if this was documented somewhere, I did look into it. Snes9xgx wii seems to require 512x512 as well. Thanks!
