### ISSUE TITLE
Screenshots on fceugx still not displaying, both on Wii and NGC... snes9xgx and vbagx are working. Please fix and a big thank you for your work !

### ISSUE THREAD

**Issue by sushimehl** [dborth/fceugx#441]

**Comment by dborth** [comment]
I can't reproduce this. Are you sure you have the settings right to load from covers vs screenshot folder? Perhaps attach a screenshot image that won't load to this issue and I can tell you why?

**Comment by sushimehl** [comment]
Thanks for your reply.
I'm pretty sure, it's the same folder structure like the others have, right? 
Only fceugx doesn't work for me, both on Gamecube and Wii...
I checked everything, don't know why. The screenshot images don't appear.

![IMG_20210326_114857](https://user-images.githubusercontent.com/35766134/112622200-01363600-8e2b-11eb-8f6e-b9b92a77acab.jpg)
![IMG_20210326_114409](https://user-images.githubusercontent.com/35766134/112622189-fd0a1880-8e2a-11eb-8f2c-5faa537d592f.jpg)
![IMG_20210326_114424](https://user-images.githubusercontent.com/35766134/112622196-fed3dc00-8e2a-11eb-8efc-4585beb73728.jpg)

**Comment by sushimehl** [comment]
The last working version of fceugx (with screenshots displaying for me) was actually 3.4.3 ...

**Comment by dborth** [comment]
if you make a new screenshot does that work? maybe your SD card is corrupted?

at a bit of a loss because the recent screenshot problems were long after 3.4.3, they were a different issue.

**Comment by sushimehl** [comment]
No, I checked everything... Can't tell where's the problem. If it works for you and others I should have made a mistake, but I really checked everything more than twice and can't find it. Just the same like the other emulators, but screenshots work only for them on both Consoles. For snes9gx it was version 4.4.4 which worked last for screenshots. vbagx I don't know anymore.

I now started telling you this issue because it should be already fixed, but it's nothing new for me... Only that now snes9x and vbagx are working again since your last updates with screenshots and fceugx does not... It's not a big problem of course, I'm just wondering why. With vbagx I still have problems with games running smoothly... the other emulators just run fine (except Yoshi's Island on snes9gx NGC)...

**Comment by l0r3n2o** [comment]
I'm having the same problem on my 4.3E Wii with FCE Ultra GX only. I tried to capture a new screenshot, it asked me to overwrite the pre-existing one but then no image shows up. If I go in the screenshots folder with WiiXplorer, the new file is there and I can open it with the built-in image viewer. I checked my Wii cIOSes with SysCheck and they're all good.

**Comment by duxiuxing** [comment]
Screenshots on fceugx still not displaying, because the code set maxwidth=640 maxheight=480 when calling DecodePNGFromFile()

```c
u8 * DecodePNGFromFile(const char *, int *, int *, u8 *, int maxwidth, int maxheight);

if(DecodePNGFromFile(imagePath, &width, &height, imgBuffer, 640, 480))
{
  preview.SetImage(imgBuffer, width, height);
  preview.SetScale( MIN(225.0f / width, 235.0f / height) );
}
else
{
  preview.SetImage(NULL, 0, 0); // <- this is why not displaying
}
```

**Comment by dborth** [comment]
640x480 should be plenty. I don't believe a game screenshot can be larger than that?

**Comment by Naugrimohtar** [comment]
Sometimes they are pulled from launchbox installs that pull higher resolution graphics from emumovies etc. higher res I presume they the look well on a 1080 or 4K tv for people using other platforms.
