### ISSUE TITLE
GameCube version can't get past either "Loading DVD", or "Exception (DSI) occurred!"

### ISSUE THREAD

**Issue by Tman2097** [dborth/fceugx#446]
Whenever I open the app, the first thing to come up is the "Loading DVD" prompt, the disc drive spins up, and the message never goes away.  (The disc in the drive is my Swiss 0.5 boot disc; my GameCube is modded with a Xeno chip)

I've tried different things to try and get around Loading DVD, such as launching the app with the disc lid open, but doing that causes it to crash to "Exception (DSI) occurred!".

I've tried loading it from SP2, and an SD Gecko in slot B.  No matter what I try and do, I can't for the life of me get around either of these two issues.  

This happens with the three main emus btw: this one, S9xGX, and VBAGX.

**Comment by SoraxOriginali** [comment]
Dusted off my GameCube to do the picoboot mod. Then hoped to use it for emulation but am running into this exact issue. The emulators all spin endlessly at Loading DVD and never allow for selection or changing settings. I'm considering looking into the code to see if I can offer a PR.

**Comment by Auisce** [comment]
> Dusted off my GameCube to do the picoboot mod. Then hoped to use it for emulation but am running into this exact issue. The emulators all spin endlessly at Loading DVD and never allow for selection or changing settings. I'm considering looking into the code to see if I can offer a PR.

Same.
Picoboot.
fceugx and snes9xgx both stuck at "loading dvd".

**Comment by tsoares37** [comment]
The problem occurs on SD cards in exFAT format. Format the SD card in FAT32 file system and the problem to start the emulator will be solved.
