### ISSUE TITLE
Super Mario Bros. textures incorrect

### ISSUE THREAD

**Issue by vaderag** [dborth/fceugx#447]
**Describe the bug**
The Textures on SMB do not show the correct image on the power up ? boxes 

**To Reproduce**
Steps to reproduce the behavior: Loading on Gamecube via Swiss

**Expected behavior**
Correct Textures

**Screenshots**
Will try grab later

**Comment by saulfabregwiivc** [comment]
Why you don't try using the official VC release instead, which is optimized?

And if you know about hex editing, you could change the color palette to it for replace the dark Wii VC palette to a brighter one, here in this post: https://gbatemp.net/threads/tutorial-replacing-the-nes-color-palette-in-wii-virtual-console-games.590714/

This issue should be closed, but let's see @dborth's decision first... :P

**Comment by dborth** [comment]
Maybe you have a bad rom, no idea. But there's nothing wrong with the emulation for SMB

**Comment by vaderag** [comment]
Playing on gamecube... it's definitely broken

**Comment by vaderag** [comment]
> Why you don't try using the official VC release instead, which is optimized?
> 
> And if you know about hex editing, you could change the color palette to it for replace the dark Wii VC palette to a brighter one, here in this post: https://gbatemp.net/threads/tutorial-replacing-the-nes-color-palette-in-wii-virtual-console-games.590714/
> 
> This issue should be closed, but let's see @dborth's decision first... :P

If I were playing on Wii, sure but as stated I'm playing on gamecube... it's definitely broken. Rom is sound

**Comment by vaderag** [comment]
Hmm... after a bit more digging seems it's some rubbish to do with a 25th anniversay or something... nevermind

**Comment by saulfabregwiivc** [comment]
The 25 number which replaced the ? in the ? blocks means that it was for conmemorate the SMB 25th Anniversary in 2010.
