### ISSUE TITLE
[Issue]: Won’t recognize USB drive. 

### ISSUE THREAD

**Issue by Jashun44** [dborth/fceugx#464]
### Describe the bug

When I switch the settings to load games from my USB drive, I get the error “USB drive not found!”  However, my drive works fine with WiiFlow and Nintendont. I’m running the latest version of FCE Ultra GX, 3.5.1. My drive is FAT32 and plugged into bottom port. HBC is running on IOS58. 

Any help is appreciated! Thank you!!

### To Reproduce

Select games to load from USB

### Expected behavior

To see my USB drive directory.

**Comment by saulfabregwiivc** [comment]
Could you try using the latest builds of FCEUGX from here?: https://github.com/dborth/fceugx/actions

**Comment by dborth** [comment]
Sorry, the USB support is as good as it's going to get. Closing.
