### ISSUE TITLE
[Issue]: APU pitch sweep not correct

### ISSUE THREAD

**Issue by zoinknoise** [dborth/fceugx#465]
### Describe the bug

pitch sweep doesn't start high enough after a KO in Punch-Out. sounds almost more like beeping instead of the super-fast downward pitch sweep as heard on real hardware. happens with 3.5.1 and the latest nightly from Feb 27.

### To Reproduce

play Punch-Out and knock down Glass Joe.

### Expected behavior

the sound that plays when the opponent falls should be a very fast downward pitch sweep spanning several octaves.

**Comment by dborth** [comment]
this is likely a bug in the upstream emulator (FCEUX). Regardless, sorry I have no intention to fix this myself. If someone wants to submit a PR that does, I'm happy to merge it!

**Comment by zoinknoise** [comment]
i understand. this issue was actually fixed in FCEUX v2.3.0, which is why i reported the bug here.

**Comment by saulfabregwiivc** [comment]
> i understand. this issue was actually fixed in FCEUX v2.3.0, which is why i reported the bug here.

Try using this fork of FCE Ultra GX made by Tanooki16, FCEUX TX. It's based on most recent FCEUX 2.6.4. https://gbatemp.net/threads/fceugx-1up.558023/

**Comment by saulfabregwiivc** [comment]
I think this is fixed on FCEUGX with this commit: https://github.com/dborth/fceugx/commit/f7306d1f412914edf3bdb15bf08d85338be9da3b
