### ISSUE TITLE
[Issue]: Audio hiss / pop when entering menu

### ISSUE THREAD

**Issue by minsec7829** [dborth/fceugx#469]
### Describe the bug

Whenever I exit the menu during gameplay, there is an irritating and fairly loud hiss / pop sound. This concerns me, as I plan on hooking some good speakers up to this display and I don't want to damage them.

### To Reproduce

Enter the menu during gameplay, then exit.

### Expected behavior

I would expect the hiss / pop not to be there.

**Comment by dborth** [comment]
the only pop sound I'm aware of is when the game timing is changed - and should only happen once, not every time. this is coming from fceux itself - not sure how to make it completely go away.

 are you changing the timing?

**Comment by dborth** [comment]
see:
https://github.com/dborth/fceugx/commit/cff27827f7f8dab4d0e5acfc942c2e3107d66f06
https://github.com/dborth/fceugx/commit/8b8f4657941a96793d0acf419fdbf259f0fbbd27

**Comment by dborth** [comment]
ah I see it now, if I change the rendering to original and my video mode to 480p.
what do you have the rendering and video mode set to?
