### ISSUE TITLE
[Issue]: Original mode 480p - Home button in game menu not working (black screen) then red tint to image

### ISSUE THREAD

**Issue by mtothaj** [dborth/fceugx#472]
### Describe the bug

With rendering set to Original and display mode to 480p the Home button in game menu does not work. Pressing Home button in game produces a black screen and another press of the Home button brings back the game but it has a red tint to the image. No way to exit the emulator / change game etc. without power cycling the Wii. 
Tested on CRT display

### To Reproduce

1. Set g rendering mode to Original and display mode to 480p 
2.Start any game.
3.Hit the Home button to bring up the emulator menu.
4.Black screen instead of menu
5. Pressing Home button again brings back game but with a red tint to the image

### Expected behavior

Pressing Home button in game should bring back the in game emulator menu

**Comment by dborth** [comment]
this is working fine for me. if it's not working for you it's something to do with your TV - and since I'm not experiencing it I can't try updating the code to fix it.
