### ISSUE TITLE
[Issue]: Buttons in FCE Ultra GX GUI stops working in v3.5.2, Forced to reset Wii to load different game

### ISSUE THREAD

**Issue by BlackPaladin2022** [dborth/fceugx#473]
### Describe the bug

I don't know if anyone else is having this issue with FCE Ultra GX, but this has been happening since the most recent version was released.  When trying to switch games, the menus stick, and I cannot choose a different game or return to the game I booted up before pressing the home button.

### To Reproduce

1.  Turn on Nintendo Wii
2.  Boot up FCE Ultra GX
3.  Boot up any game to play on FCE Ultra GX
4.  Press the home button
5.  Use the Wiimote to press any button on the screen.  (You'll hear the clicking sound on-screen when the button is pressed, but nothing changes.  The button cannot even be pushed again.  This happens with all buttons on-screen "Save", "Load", etc.  This issue happens when loading any game and pressing the Home button on Wiimote.)

### Expected behavior

When pressing the buttons on FCE Ultra GX's GUI, they should work as intended.  Instead, after the button is pressed once, it cannot be pressed again, and the screen becomes stuck, unable to exit, return to the game, or choose a different game.

I've had this issue happen recently when in the "Choose Game" menu... but only after exiting a game I had booted up successfully.  (Which surprised me as this was the first time in some time that this happened.  But when the buttons on the "Choose Game" menu wouldn't work, it was back to square one for me.)

Right now, the only workaround I have with this issue is to just press and hold the power button on the Wii for a few seconds and press it again to power it back on.  However, I can only hope this error can be fixed soon.

**Comment by dborth** [comment]
Are your games on SD or USB?
