### ISSUE TITLE
[Issue]: Out of memory: too many files!

### ISSUE THREAD

**Issue by Chipsum** [dborth/fceugx#483]
### Describe the bug

Out of memory: too many files!

### To Reproduce

Had a full no intro set (about 3075 ROMS) in the roms file.

### Expected behavior

Normal

### Screenshots

![image](https://user-images.githubusercontent.com/37517008/210112644-e4c8f28f-32af-41df-9ad8-79cc706c1623.png)

**Comment by dborth** [comment]
This is expected. You'll have to split your ROMs into multiple folders.
