### ISSUE TITLE
[Issue]: FDS BIOS fails to load FDS games in FCE Ultra GX 3.5.3

### ISSUE THREAD

**Issue by BlackPaladin2022** [dborth/fceugx#493]
![IMG_1256](https://github.com/dborth/fceugx/assets/99116758/b689f604-2ad2-441b-bc83-9e5e9b81eb58)
### Describe the bug

I love the latest version of FCE Ultra GX, but the latest version of the emulator (3.5.3) does have one issue that I find annoying.  When tried to load FDS games, even when the BIOS is properly installed, won't run any FDS games at all.  I've replaced it the bios files that wasn't on the SD card (disksys.rom) and when loading the game after replacing the BIOS it does work, but after closing the emulator and opening it at a later date, the issue resumes, and FDS games cannot run.  (This issue only occurs with FDS games.  NES games are unaffected.)

This error will occur whether the FDS game is either in the SD card or on an external hard drive.

### To Reproduce

1.  Make sure the file "disksys.rom" is properly installed
2.  Run FCE Ultra GX 3.5.3 on a modded Nintendo Wii
3.  Open any FDS ROM.  (It doesn't matter if the game was patched or not)
4.   A gray screen would be visible, no game play or FDS bios displaying.

### Expected behavior

When loading any FDS game on FCE Ultra GX, a gray screen would appear and the game will not run.  This happens with any FDS game, patched or unpatched.

**Comment by BlackPaladin2022** [comment]
For the record, I have the file "disksys.rom" on both the USB card and on the external hard drive, both on their respective "fceugx" folder.  While FDS ROMs on the SD card run normally, FDS files on the external hard drive either display the screen above which I pictured, or I receive  the message "FDS BIOS cannot be found". (or something to that effect)

**Comment by dborth** [comment]
This sounds like a usb problem only. Perhaps the drive is going to sleep. The USB support on Wii isn't the best. I'd suggest to stick with SD if that works.
