### ISSUE TITLE
[Question]: What file should be used as a template/basis for translation?

### ISSUE THREAD

**Issue by MayanKoyote** [dborth/fceugx#496]
### Describe your question

I have an opportunity to make a translation into one of the languages for which there is no translation.
And I immediately had a question: what file should I use as a template/basis for translation?

The English file is empty, it's dummy.

The last (by time) of the ones found in pull requests is German.
But it doesn't have, for example:
msgid "Artwork Folder", msgid "Delete Saves", msgid "Filtered (Soft)", msgid "Chinese (Simplified)" and a whole bucket of other lines that are present in the program text.
Conversely, there are strings like:
msgid "Compressed GBA files are not supported!", msgid "Out of memory!" (and lot of others) which are not present in the program text (out of date as I understand it).

The next most recent edit is Spanish. It seems to be more up to date, but... I want to be sure that everything that needs to be translated is there and there is nothing that no longer needs to be translated.

Is it possible to get an indication/confirmation of which file is better to use as a template/basis for translation?

**Comment by dborth** [comment]
Unfortunately there is no definitive list - that's what the English file is supposed to be for though. If there's additional translations in the file, they're just ignored. Some translators have used this to create a single translation file shared between all 3 emulator projects. If you wanted to be ridiculously thorough, you could find the unique subset of all of the files, or dig through the code and manually compile a list but no one has done that (aside from when I originally put together a list).
