### ISSUE TITLE
[Issue]: Options mismatched within UI causing weird input and backward options

### ISSUE THREAD

**Issue by MasterFox2492** [dborth/fceugx#500]
### Describe the bug

When bringing up the application menu during a game after selecting Main menu you provided two options. "OK" and "Cancel". "OK" is highlighted by default, however the option for "OK" when selected with the A button actually ends up doing what the cancel option should do and takes you back to the application menu. Then when you Try to push right on the d-pad the highlight will not move to the right to select "Cancel". Only when pushing left on the d-pad will the highlight move right to the "Cancel" option. and when you press A on this option it does what "OK" should do and take you back to the game selection screen.

### To Reproduce

Open a game and bring up the application menu by pressing L + R + Start
Select "Main Menu"
Attempt to select both OK and Cancel

### Expected behavior

OK should be OK instead of Cancel, Cancel should be Cancel instead of OK, and right should move the selection right, instead of left moving the selection right.

**Comment by dborth** [comment]
Sounds like you're just confused over the chosen colors for selected vs not selected. Closing.
