### ISSUE TITLE
[Issue]: Wrong Button mapping on the Wii U Gamepad

### ISSUE THREAD

**Issue by abanaboy** [dborth/fceugx#503]
### Describe the bug

When quitting a game on the Wii U, i have to select "cancel" instead of "OK". 
The left and right control pad button is also reversed in that case.

### To Reproduce

.

### Expected behavior

.

**Comment by dborth** [comment]
Are you saying that left and right are mixed up everywhere? Only for the Wii u gamepad or for all controller types? Everywhere in the menu or just the prompt? What about when playing games? Does this happen on the other emulators, ie snes9x gx?

**Comment by abanaboy** [comment]
The issue is only present in the quitting prompt. Snes9x has the same problem. Vbagx is fine.
I have attached a video:

https://github.com/dborth/fceugx/assets/159199749/a6480f55-156d-403b-aa92-f8ceb5bb9b4d

**Comment by dborth** [comment]
Thanks for the video. Looks like it's functioning as expected and you're just confused about the highlight color - yellow is the selected entry. Many people have flagged this.

**Comment by abanaboy** [comment]
If many people have flagged this then why not changing the color scheme? Would be cool if you could make a change on the colors in the prompt for SNES and NES to avoid confusion.
