### ISSUE TITLE
New skins 

### ISSUE THREAD

**Issue by DIVINIUM-115** [dborth/fceugx#506]
### Describe your question

Hello, I would like to design skins for emulators in the 2024 Nintendo Switch Online style for GBA Advance, SNES, and NES emulators. I am a graphic designer, and I've had this idea for two years since the launch of the Nintendo Switch Online service. I'd like to create a new menu to give these emulators a more modern feel. If you're interested, send me a message on my Discord, Divinium115. I'll be waiting. ☺️

**Comment by dborth** [comment]
So the challenge with this is that you will either have to keep all the image sizes identical or there will need to be reworking of the code (the math calculations for placement) to accommodate the new dimensions. If you download the source code you'll find all the images that get used to draw the UI. If you still want to create an alternative set, I'd suggest to start there and make the set to be swapped in and then reply in this issue.
