### ISSUE TITLE
[Question]: Digital Prime (FBX) Import

### ISSUE THREAD

**Issue by TheBeverage** [dborth/fceugx#508]
### Describe your question

Hi,

I believe it would be possible to add the Digital Prime (FBX) palette -- FirebrandX's "final" palette, and the one used on the NESRGB3 -- into FCEUGX based on the work done by saulfabreg on FCEUTX. Here is the part from gcvideo.gpp that I believe would need to be added under "struct st_palettes palettes[] ":

`	{ "digital-prime-fbx", "FBX's Digital Prime",
		{ 0x696969, 0x00148F, 0x1E029B, 0x3F008A,
		    0x600060, 0x660017, 0x570D00, 0x451B00,
		    0x243400, 0x004200, 0x004500, 0x003C1F,
		    0x00315C, 0x000000, 0x000000, 0x000000,
		    0xAFAFAF, 0x0F51DD, 0x442FF3, 0x7220E2,
		    0xA319B3, 0xAE1C51, 0xA43400, 0x884D00,
		    0x676D00, 0x208000, 0x008B00, 0x007F42,
		    0x006C97, 0x010101, 0x000000, 0x000000,
		    0xFFFFFF, 0x65AAFF, 0x8C96FF, 0xB983FF,
		    0xDD6FFF, 0xEA6FBD, 0xEB8466, 0xDCA21F,
		    0xBAB403, 0x7ECB07, 0x54D33E, 0x3CD284,
		    0x3EC7CC, 0x4B4B4B, 0x000000, 0x000000,
		    0xFFFFFF, 0xBDE2FF, 0xCECFFF, 0xE6C2FF,
		    0xF6BCFF, 0xF9C2ED, 0xFACFC6, 0xF8DEAC,
		    0xEEE9A1, 0xD0F59F, 0xBBF5AF, 0xB3F5CD,
		    0xB9EDF0, 0xB9B9B9, 0x000000, 0x000000 }
	},`

I am no programmer so I apologize if this is not as simple as it would appear! Thanks again for keeping up work on this excellent port after so many years.

**Comment by dborth** [comment]
Added.
