### ISSUE TITLE
FDS games refuse to work

### ISSUE THREAD

**Issue by pokemonfan6498** [dborth/fceugx#509]
### Describe the bug

i was trying to play super mario bros 2 but i only got a gray screen and nothing else and this happens woth every game even if i had bios present can anyone explain what causes this?

### To Reproduce

it appears by launching any fds image whatever it's a clear dump or a hacked rom

### Expected behavior

i expected fceuxgx to launch games like fceuxtx and since the newest update released i thought it would do things like fix sound and graphics in certain games

**Comment by dborth** [comment]
Ask on a forum like gbatemp. This isn't the place.
