### ISSUE TITLE
[Issue]: game genie doesn’t work :(

### ISSUE THREAD

**Issue by samuelwhitcombhyde** [dborth/fceugx#510]
### Describe the bug

I added gg.nes to every folder possible and it doesn’t enable in settings. I tried Game Genie.nes and that didn’t work either. I looked for solutions online and none worked or even made sense. I’m on 3.5.4, clean install basically. Normal cheats work fine.

### To Reproduce

Install gg.nes to every folder possible, won’t enable in settings. 

### Expected behavior

I expected it to work when I added it to roms folder. I loaded the rom and it also doesn’t do anything but reset after entering a code.

### Screenshots

![23DD2208-BB5A-4855-A737-A104CD1702C6](https://github.com/dborth/fceugx/assets/125171490/b432c7a6-0e48-4621-94d2-408bcff3b10f)

**Comment by dborth** [comment]
gg.rom not gg.nes

**Comment by samuelwhitcombhyde** [comment]
> gg.rom not gg.nes

Wtf I feel so dumb, why could I not figure that out!! Thank you. Got it working. This emulator is great!
