### ISSUE TITLE
[Issue]: FDS games don't load even if sysdisk.rom is included.

### ISSUE THREAD

**Issue by AndriuxDev** [dborth/fceugx#511]
### Describe the bug

_Issue reported on version 3.5.4, which was released on March 30, 2024._

Famicom Disk System (FDS) games, including "Super Mario Brothers 2 (Japan)," do not load in FCEUGX despite the _sysdisk.rom_ file being present in the appropriate directory. Upon selecting the game, it'll either load the game or be stuck in a grey screen. This issue occurs consistently across various FDS titles.

### To Reproduce

1. Open FCEUGX.
2. Ensure that the sysdisk.rom file is located in X:/fceugx/.
3. Select an FDS game to load.
4. Attempt to start the game.

***X:** indicates that the directory is a placeholder for any drive or location, providing flexibility for different user setups.

### Expected behavior

FCEUGX should successfully load the FDS games, allowing for normal gameplay when the sysdisk.rom file is present.

**Comment by dborth** [comment]
Just tested it, working fine for me. Closing.

**Comment by AndriuxDev** [comment]
If it's working for you, then what am I doing wrong? What's the right procedure to follow to play FDS games on FCEUGX?

**Comment by dborth** [comment]
Maybe you have the wrong sysdisk.rom. should be 8kb. I'd suggest to ask on gbatemp

**Comment by saulfabregwiivc** [comment]
the name is **disksys.rom**, not sysdisk.rom

**Comment by AndriuxDev** [comment]
> Maybe you have the wrong sysdisk.rom. should be 8kb. I'd suggest to ask on gbatemp
> the name is **disksys.rom**, not sysdisk.rom

I checked the drive where I have it. It's indeed called "disksys.rom" and it weighs exactly 8KB. Perhaps something else is wrong?
![image](https://github.com/user-attachments/assets/03def567-ea53-4c9e-9de0-581d6f1d33fb)

**Comment by roo1234** [comment]
I have this same problem. All disk system games gives grey screen on 3.5.4. Reverting to 3.5.2 has solved the problem, will try now 3.5.3.
I have the disksys.rom file placed everywhere (roms\NES, fceugx root and apps).
